<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/add.css" );
$this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/selectBox.js');

echo $this->form;
?>

<script type="text/javascript">
Event.observe(window, 'load', init, false);

function init() {
     select = new SelectBox('<?php echo $this->objSelectBox ?>');
}
</script>

