<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/modules/default/css/datepicker.css");
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/datepicker.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/prototype-date-extensions.js", 'text/javascript');

$locale = str_replace("_", "-", Snep_Locale::getInstance()->getLocale());
if( $locale == "en-US") { $locale = 'en_US'; }

echo $this->form;
?>
<script type="text/javascript"> 
  new Control.DatePicker('init_day', {icon: '<?php echo $this->baseUrl(); ?>/modules/default/img/calendar.png', timePicker: true, timePickerAdjacent: true, locale: '<?php echo $locale; ?>'});
  new Control.DatePicker('end_day', {icon: '<?php echo $this->baseUrl(); ?>/modules/default/img/calendar.png', timePicker: true, timePickerAdjacent: true, locale: '<?php echo $locale; ?>'});
</script>
 