<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/index.css" );
$this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/removeItem.js');
echo $this->render('filter.phtml')
?>

<table cellspacing="0" cellpadding="0" border="0" align="center" width="100%" >
   <thead>
      <tr>
         <th> <?php echo $this->translate('Código') ?> </th>
         <th> <?php echo $this->translate('Nome') ?> </th>
         <th> <?php echo $this->translate('Tipo') ?> </th>
         <th> <?php echo $this->translate('Descrição') ?> </th>
         <th colspan="2" class="action"> <?php echo $this->translate('Ações') ?> </th>
      </tr>
   </thead>
   <tbody>
    <?php
    $c = 0;
    if( $this->costcenter ) :
        foreach($this->costcenter as $id => $costcenter ): ?>
            <?php ($c ? $c = 0 : $c = 1 ); ?>
            <tr class="c<?php echo $c ?>">
                <td> <b> <?php echo $costcenter['codigo'] ?> </b> </td>
                <td> <?php echo $costcenter['nome'] ?> </td>
                <td> <?php echo $this->types[$costcenter['tipo']] ?> </td>
                <td> <?php echo $costcenter['descricao'] ?> </td>
                <td class="action">
                    <a class="alterar" href="<?php echo $this->url ?>/edit/id/<?php echo $costcenter['codigo'] ?>">
                        <?php echo $this->translate('Alterar')?>
                    </a>
                </td>
                <td class="action" class="display:inline;">
                    <?php $this->remove_msg = $this->translate("Deseja remover este item?");?>
                    <span class="excluir" onclick="remove_item('<?php echo $this->url ?>','<?php echo $costcenter['codigo'] ?>','<?php echo $this->remove_msg ?>')">
                        <?php echo $this->translate('Excluir')?>
                    </span>
                </td>
            </tr>
        <?php endforeach ?>
    <?php endif?>
</table>

<?php echo $this->render('pagination.phtml') ?>