<?php
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/src/scriptaculous.js');
$this->headScript()->appendFile('/snep/includes/javascript/registrations.js');
echo $this->render('filter.phtml')

?>

<table cellspacing="0" cellpadding="0" border="0" align="center" width="100%" >
   <thead>
      <tr>
         <td class="action"> <?php echo $this->translate('Código') ?> </td>
         <td> <?php echo $this->translate('Nome') ?> </td>
         <td> <?php echo $this->translate('Grupo') ?> </td>
         <td class="action" colspan="2"> <?php echo $this->translate('Ações') ?> </td>
      </tr>
   </thead>
   <tbody>
    <?php
    $c = 0;
    if($this->contactsgroups):
        foreach($this->contactsgroups as $cha => $val ): ?>
            <?php ($c ? $c = 0 : $c = 1 ); ?>
            <tr class="c<?php echo $c ?>">
                <td> <b> <?php echo $val['id'] ?> </b> </td>
                <td> <?php echo $val['name'] ?> </td>
                <td class="action">
                    <a class="alterar" href='/snep/src/contacts_group.php?acao=alterar&cod_grupo=<?php echo $val['id'] ?>'>
                        <?php echo $this->translate('Alterar')?>
                    </a>
                </td>
                <td class="action">
                    <span class="excluir"  onclick="remove_item('/snep/src/contacts_group.php?acao=excluir&cod_grupo=<?php echo $val['id'] ?>', '<?php echo $this->translate('Deseja realmente excluir o Grupo de Contatos?')?>')" >
                        <?php echo $this->translate('Excluir')?>
                    </span>
                </td>
            </tr>
        <?php endforeach ?>
    <?php endif ?>
</table>

<?php echo $this->render('pagination.phtml') ?>