<?php
/**
 *  This file is part of SNEP.
 *
 *  SNEP is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  SNEP is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with SNEP.  If not, see <http://www.gnu.org/licenses/>.
 */
?>

<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/debugger.css" );
?>

<form method="post" action="index">
    <table style="width: 100%;">
        <tr>
            <td style="border-bottom:none; padding: 5px;">
                <input type="hidden" name="acao" value="simulate" />
                <label for="srcType"><?php echo $this->translate('Source') ?>:</label>
                <select id="srcType" class="campos" name="srcType" onchange="if(this.value == 'trunk') $('trunk').show(); else $('trunk').hide();">
                    <option <?php echo isset($_REQUEST['srcType']) && $_REQUEST['srcType'] == 'exten' ? "selected" : "" ?> value="exten"><?php echo $this->translate("Extension"); ?></option>
                    <option  <?php echo isset($_REQUEST['srcType']) && $_REQUEST['srcType'] == 'trunk' ? "selected" : "" ?> value="trunk"><?php echo $this->translate("Trunk"); ?></option>
                    <option  <?php echo isset($_REQUEST['srcType']) && $_REQUEST['srcType'] == 'undefined' ? "selected" : "" ?> value="undefined"><?php echo $this->translate("Undefined"); ?></option>
                </select>
                <select id="trunk" name="trunk" style="<?php echo isset($_REQUEST['srcType']) && $_REQUEST['srcType'] == 'trunk' ? "" : "display:none;" ?>">
                    <?php
                    foreach ($this->trunks as $key => $value) {
                        echo "<option value='$key' > $value </option>";
                    }
                    ?>
                </select>
                <input type="text" name="caller" id="caller" class="campos" value="<?php echo isset($_REQUEST['caller']) ? $_REQUEST['caller'] : ""; ?>" />
                       <label for="dst"><?php echo $this->translate('Destiny') ?>:</label>
                    <input type="text" name="dst" class="campos" id="dst" value="<?php echo isset($_REQUEST['dst']) ? $_REQUEST['dst'] : ""; ?>" />
                <label for="time"><?php echo $this->translate('Time') ?>:</label>
                    <input type="text" size="5" name="time" id="time" class="campos" value="<?php echo isset($_REQUEST['time']) ? $_REQUEST['time'] : ""; ?>" /> (hh:mm)  
            </td>
        </tr>
        <tr>
            <td style="border-top:none; padding: 5px;">
                <input type="submit" value="<?php echo $this->translate('Simulate') ?>" class="button">
                <a id="voltar" class='snep_form_cancel' href="<?php echo $this->baseUrl() ?>/index.php/default/route"><?php echo $this->translate('Cancel') ?></a>
            </td>
        </tr>
        <?php if ($this->result){ ?>
        <tr>
            <td>
                <ul id="input">
                    <li><strong><?php echo $this->translate('Source') ?>:</strong> <?php echo $this->input['caller'] ?></li>
                    <li><strong><?php echo $this->translate('Destiny') ?>:</strong> <?php echo $this->input['dst']  ?></li>
                    <li><strong><?php echo $this->translate('Time') ?>:</strong> <?php echo $this->input['time'] ?></li>
                </ul>
            </td>
        </tr>
        <tr>
            <td style="text-align:left;">
                <ul id="results">
                   <?php foreach ($this->result as $key => $value) { ?>
                    <li class="rule <?php echo $value['state'] ?>">
                        <ul class="info">
                            <li class="execute"><strong><?php echo $this->translate('Actions to execute') ?>:</strong>
                                <ul>
                                    <?php
                                    foreach ($value["actions"] as $key2 => $valueAct) { ?>
                                    <li><?php echo $valueAct ?></li>
                                    <?php } ?>
                                </ul>
                            </li>
                            <li class="desc"><?php echo $this->translate("Rule: %s %s", $value['id'], $value['desc']); ?></li>
                            <li class="caller"><?php echo $this->translate('Source: %s', $value['caller']);?></li>
                            <li class="dst"><?php echo $this->translate('Destiny: %s', $value['dst']);?></li>
                            <li class="valid"><?php echo $this->translate('Validity: %s', $value['valid']);?></li>
                        </ul>
                    <li>
                        <?php } ?>
                </ul>
            </td>
        </tr>
        
        <tr>
            <td>
                <ul id="legenda">
                    <li class="torun"><?php echo $this->translate('Rule that will be executed')?></li>
                    <li class="outdated"><?php echo $this->translate('Rule invalid because of time')?></li>
                    <li class="ignored"><?php echo $this->translate('Rule ignored by priority')?></li>
                </ul>
            </td>
        </tr>
         <?php } ?>
    </table>
</form>
