<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/modules/default/css/main.css" );
$this->headLink()->appendStylesheet( $this->baseUrl() . "/modules/default/css/add.css" );
$this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/functions_smarty.js');
$this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
?>

<?php
    echo $this->form;
?>

