<form name="formulario" method="POST" action="<?php echo $this->BaseUrl ?>/contacts/csvfinish">
    <table width="100%">
        <thead>
            <tr>
                <?php
                $csvarq = $this->csvprocess;
                foreach ($csvarq[0] as $ind => $linha): ?>
                    <th>
                        <select name="field[<?php echo $ind ?>]">
                        <?php foreach ($this->fields as $field => $name) : ?>
                            <option value="<?php echo $field; ?>"><?php echo $name; ?></option>
                        <?php endforeach ?>
                        </select>
                    </th>
                <?php endforeach ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($csvarq as $ind => $linha) : ?>
            <tr>
                <?php foreach ($linha as $item) : ?>
                    <td><?php echo $item ?></td>
                <?php endforeach ?>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>

    <div id="main_container" style="border-top: none;">

        <p style="text-align: center; margin: 0px; padding: 5px;">

            <label for="group">
                <?php echo $this->translate("Grupo"); ?>
            </label>

            <select id="group" name="group" class="campos">
                <?php foreach ($this->group as $id => $group) : ?>
                        <option value='<?php echo $id ?>'><?php echo $group ?></option>
                <?php endforeach ?>                
            </select>
                <br />
            <input type="checkbox" name="discard_first_row" id="discard_first_row" />

            <label for="discard_first_row">
                    <?php echo $this->translate("Descartar Primeira Linha"); ?>
            </label>
                <br />
        </p>
    </div>
</form>

<div class="button_bar">
    <input class="new_button" type="submit" id="salvar" value="Salvar" onclick="formulario.submit();" />

    <button onclick="location.href='<?php echo $this->BaseUrl;?>/contacts/csv/;'" >
        <?php echo $this->translate("Cancelar"); ?>
    </button>
</div>
