<script type="text/javascript" src="<?php echo $this->pathweb ?>/includes/javascript/scriptaculous/src/scriptaculous.js"></script>
<script type="text/javascript" src="<?php echo $this->pathweb ?>/includes/javascript/scriptaculous/src/effects.js"></script>
<script type="text/javascript" src="<?php echo $this->pathweb ?>/includes/javascript/scriptaculous/src/dragdrop.js"></script>
<script type="text/javascript" src="<?php echo $this->pathweb ?>/includes/javascript/contacts.js"></script>

<?php if( $this->number_error ) : ?>
    <div class="error_box">
        <?php echo $this->number_error ?>
    </div>
<?php endif ?>

<?php echo $this->form ?>

<script type="text/javascript">
    <?php foreach($this->phones as $phone) : ?>
        <?php echo "newphone('$phone');\n" ?>
    <?php endforeach ?>
</script>