<?php
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/src/scriptaculous.js');
$this->headScript()->appendFile('/snep/includes/javascript/enableField.js');
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/datepicker.css");
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/datepicker.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/includes/javascript/prototype-date-extensions.js", 'text/javascript');
$locale = str_replace("_", "-", Snep_Locale::getInstance()->getLocale());
if( $locale == "en-US") { $locale = 'en_US'; }
?>
<?php
echo $this->form;
?>
<script language="javascript" type="text/javascript">
$( 'exten-group_select').observe ('change' , init);

function init() {    
enableField('exten-group_select', 'exten-exten_select')
}
</script>
<script type="text/javascript"> 
  new Control.DatePicker('period-init_day', {icon: '<?php echo $this->baseUrl(); ?>/imagens/calendar.png', timePicker: true, timePickerAdjacent: true, locale: '<?php echo $locale; ?>'});
  new Control.DatePicker('period-till_day', {icon: '<?php echo $this->baseUrl(); ?>/imagens/calendar.png', timePicker: true, timePickerAdjacent: true, locale: '<?php echo $locale; ?>'});
</script>
 

