<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/index.css" );
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/src/scriptaculous.js');
$this->headScript()->appendFile('/snep/includes/javascript/registrations.js');
?>

  <table>
	 <tr>
		 <td colspan="2">
			<b><?php echo $this->filter;?></b>
		 </td>
	  </tr>
	 <tr>
		<td class="esq" width="15%">
		<strong><?php echo $this->origin;?></strong>
		</td>
		<td class="esq">
			<?php echo $this->sinteticsrc; ?>
		</td>
	 </tr>
	 <tr>
		<td class="esq" width="15%">
		<strong> <?php echo $this->destination; ?></strong>
		</td>
		<td class="esq">
			<?php echo $this->sinteticdst; ?>
		</td>
	 </tr>
	 <tr>
		<td class="esq" width="15%"><strong> <?php echo $this->cost_center; ?></strong> </td>
		<td class="esq">
			<?php echo $this->cost_center_res ?>
		</td>
	 </tr>
	 <tr>
		<td class="esq" width="15%">
		<strong><?php echo $this->callstatus?></strong>
		</td>
		<td class="esq">
			<?php foreach ($this->status as $stat) { ?>
				<?php echo $stat ?>,
			<?php } ?>
		</td>
	  </tr>
	  <tr style="background-color: #f1f1f1;">
		 <td colspan="2">
			<b><?php echo $this->totals_sub?></b>
		 </td>
	  </tr>
	  <tr>
		 <td>
			<b><?php echo $this->calls;?></b>
		 </td>
		 <td>
			<?php echo $this->answered;?>:&nbsp;
			<b><?php echo $this->totals['answered'];?></b>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<?php echo $this->nanswered;?>:&nbsp;
			<b><?php echo $this->totals['notanswer'];?></b>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<?php echo $this->busy;?>:&nbsp;
			<b><?php echo $this->totals['busy'];?></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<?php echo $this->failure;?>:&nbsp;
			<b><?php echo $this->totals['fail'];?></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<?php echo $this->other;?>:&nbsp;
			<b><?php echo $this->totals['oth'];?></b>

		 </td>
	  </tr>
	  <tr>
		 <td>
			<strong><?php echo $this->times; ?>: (H:m:s)</strong>
		 </td>
		 <td>
			<?php echo $this->calls; ?>:&nbsp;
				<b><?php echo $this->duration_call; ?></b>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<?php echo $this->tarrifation; ?>:&nbsp;
				<b><?php echo $this->bill_sec; ?></b>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<?php echo $this->wait ?>:&nbsp;
				<b><?php echo $this->wait_call; ?></b>
		 </td>
	  </tr>
	  <?php if ($this->tariffed) { ?>
		 <tr>
			<td>
			   <strong><?php echo $this->tot_tariffed; ?></strong>
			</td>
			<td>
			   <?php echo $this->totals['tot_tarifado']; ?>
			</td>
		 </tr>
	  <?php } ?>

	  <tr class="cen">
		  <td colspan="2">
			 <input type="button" id="voltar" value="<?php echo $this->back?>" onClick="location.href='javascript:history.back(-1);'" />
		  </td>
	  </tr>
  </table>
