<meta http-equiv="refresh" content="10" />
<?php $this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js'); ?>

<style type="text/css">
.snep_form table { width: 100%; border-collapse: collapse; }
.snep_form table td, th {border: 1px solid #ccc; }
.snep_form table thead td {padding-left: 10px !important; }
</style>

<div class="snep_form">
<table cellpadding="0" cellspacing="0" align="center">
    <thead>
    <tr>
        <td><?php echo $this->translate("IP Extensions") ?></td>
        <td><?php echo $this->translate("Queues") ?></td>
    </tr>
    </thead>
   <tr>
     <!-- Extensions -->
     <td valign="top" width="60%">
        <table>
           <thead>
              <tr>
                 <td class="esq"><?php echo $this->translate("Extension") ?></td>
                 <td class="cen"><?php echo $this->translate("Type") ?></td>
                 <td class="esq"><?php echo $this->translate("IP Address") ?></td>
                 <td class="esq"><?php echo $this->translate("Latency") ?></td>
                 <td class="esq"><?php echo $this->translate("Codecs") ?></td>
              </tr>
           </thead>
           <?php
           if ($this->ramais) {
                foreach ($this->ramais as $key => $value) {
            ?>
              <tr bgcolor=''>
                 <td class="esq"><?php echo $value['ramal'] ?></td>
                 <td class="cen"><?php echo $value['tipo'] ?></td>
                 <td class="esq"><?php echo $value['ip'] ?></td>
                 <td class="esq"><?php echo $value['delay'] ?></td>
                 <td class="esq"><?php echo $value['codec'] ?></td>
              </tr>
           <?php
                }
           } else {
           ?>
              <tr bgcolor=''>
                 <td class="esq" colspan="5"><?php echo $this->translate("no extension available") ?></td>
              </tr>
           <?php
           }
           ?>
        </table>
     </td>

     <td valign="top">
        <table>
           <thead>
              <tr>
                 <td class="esq"><?php echo $this->translate("Queue") ?></td>
                 <td class="esq"><?php echo $this->translate("Members") ?></td>
                 <td class="esq"><?php echo $this->translate("Status") ?></td>
              </tr>
           </thead>
           <?php

           if ($this->filas) {
                foreach ($this->filas as $key => $value) {
            ?>
              <tr bgcolor=''>
                 <td class="esq" style="vertical-align: top;"><?php echo $value['fila'] ?></td>
                 <td class="esq"><?php echo $value['agent'] ?></td>
                 <td class="esq"><?php echo $value['status'] ?></td>
              </tr>
           <?php
                }
           } else {
           ?>
              <tr bgcolor=''>
                 <td class="esq" colspan="3"><?php echo $this->translate("no queue available") ?></td>
              </tr>
           <?php
           }
           ?>
        </table>
        <br />
        <table>
           <thead>
              <tr>
                 <td class="esq"><?php echo $this->translate("Licenses (g729)") ?></td>
                 <td class="esq"><?php echo $this->translate("Code") ?></td>
                 <td class="esq"><?php echo $this->translate("Decode") ?></td>
              </tr>
           </thead>
           <?php
                if ($this->codecs[1]) {
            ?>
              <tr bgcolor=''>
                 <td class="esq" style="vertical-align: top;"><?php echo $this->codecs[0] ?></td>
                 <td class="esq"><?php echo $this->codecs[1] ?></td>
                 <td class="esq"><?php echo $this->codecs[2] ?></td>
              </tr>
           <?php
                }else{
            ?>
              <tr bgcolor=''>
                 <td class="esq" colspan="3"><?php echo $this->translate("no data available") ?></td>
              </tr>
           <?php
                }
           ?>
        </table>
        <br />

   <!-- Trunks -->
    <table>
       <thead>
          <th colspan='5'>
             <?php echo $this->translate("SIP Trunks") ?>
          </th>
          <tr>
            <td><?php echo $this->translate("Name") ?></td>
            <td><?php echo $this->translate("IP") ?></td>
            <td><?php echo $this->translate("Status") ?></td>
            <td><?php echo $this->translate("Latency") ?></td>
          </tr>
       </thead>
           <?php
           if ($this->troncos) {
                foreach ($this->troncos as $key => $value) {
            ?>
          <tr>
               <?php
                    foreach ($value as $peerskey => $peersvalue) {
                ?>
                    <td class="esq" style="vertical-align: top;"><?php echo $peersvalue ?><br/></td>
                <?php } ?>
          </tr>
           <?php
                }
           } else {
           ?>
              <tr bgcolor=''>
                 <td class="esq" colspan="4"><?php echo $this->translate("no trunk available") ?></td>
              </tr>
           <?php
           }
           ?>
    </table>
   <br/>
   <!-- IAX2 Trunks -->
    <table>
       <thead>
          <th colspan='5'>
             <?php echo $this->translate("IAX2 Trunks") ?>
          </th>
          <tr>
            <td><?php echo $this->translate("Name") ?></td>
            <td><?php echo $this->translate("IP") ?></td>
            <td><?php echo $this->translate("Status") ?></td>
            <td><?php echo $this->translate("Latency") ?></td>
          </tr>
       </thead>
           <?php
           if ($this->iax2 != NULL) {
                foreach ($this->iax2 as $key => $value) {
            ?>
          <tr>
               <?php
                    foreach ($value as $peerskey => $peersvalue) {
                ?>
                    <td class="esq" style="vertical-align: top;"><?php echo $peersvalue ?><br/></td>
                <?php } ?>
          </tr>
           <?php
                }
           } else {
           ?>
              <tr bgcolor=''>
                 <td class="esq" colspan="4"><?php echo $this->translate("no trunk available") ?></td>
              </tr>
           <?php
           }
           ?>
    </table>
     </td>
   </tr>
</table>
<br />
</div>


