<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/index.css" );
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/scriptaculous/src/scriptaculous.js');
$this->headScript()->appendFile($this->baseUrl() . '/includes/javascript/registrations.js');
echo $this->render('filter.phtml');
?>

<table>
   <thead>
      <tr>
         <th> <?php echo $this->translate('Name') ?> </th>
         <th> <?php echo$this->translate('Tipo') ?> </th>
         <th colspan="2" class="action"> <?php echo $this->translate('Actions') ?> </th>
      </tr>
   </thead>
   <tbody>
    <?php
    $c = 0;
    if($this->extensionsgroups):
        foreach($this->extensionsgroups as $cha => $val ): ?>
            <?php ($c ? $c = 0 : $c = 1 ); ?>
            <tr class="c<?php echo $c ?>">
                <td>
                    <b>
                        <?php if(array_key_exists($val['name'], $this->tra) ) : ?>
                            <?php echo $this->tra[$val['name']]; ?>
                        <?php else : ?>
                           <?php echo $val['name']; ?>
                        <?php endif ?>
                    </b>
                </td>
                <td> 
                        <?php if(array_key_exists($val['inherit'], $this->tra) ) : ?>
                            <?php echo $this->tra[$val['inherit']]; ?>
                        <?php else : ?>
                           <?php echo $val['inherit']; ?>
                        <?php endif ?>

                </td>
                        <?php if( ! array_key_exists($val['name'], $this->tra) ) : ?>
                            <td class="action">
                                <a class="alterar" href='<?php echo $this->URL; ?>edit/id/<?php echo $val['name'] ?>'>
                                    <?php echo $this->translate('Edit')?>
                                </a>
                            </td>
                            <td class="action">
                                <a class="excluir" href='<?php echo $this->URL; ?>delete/id/<?php echo $val['name']?>'>
                                    <?php echo $this->translate("Delete"); ?>
                                </a>
                            </td>
                            <?php else : ?>
                            <td class="action"> </td>
                            <td class="action"> </td>
                            <?php endif ?>
            </tr>
        <?php endforeach ?>
    <?php endif ?>
</table>

<?php echo $this->render('pagination.phtml') ?>