<?php echo $this->doctype(); ?>
<html>
<head>
    <?php echo $this->headTitle() . "\n"; ?>
    <?php echo $this->headLink() . "\n"; ?>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headStyle() . "\n"; ?>
    <?php echo $this->headScript() . "\n"; ?>
</head>
<body>
    <div id="header">
        <a href="<?php echo Zend_Registry::get('config')->system->path->web; ?>/src/sistema.php" alt="inicio" title="inicio">
            <img src="<?php echo $this->baseUrl(); ?>/imagens/snep_logo.png" alt="SNEP" id="snep_logo" />
        </a>
    </div>
    <?php if(!$this->hideMenu): ?>
    <div id="menu">
        <?php echo $this->menu; ?>
    </div>
    <?php endif; ?>
    <div id="breadcrumb">
        <?php echo $this->breadcrumb; ?>
    </div>
    <div id="content">
        <?php echo $this->layout()->content; ?>
    </div>
    <div id="footer">
        <p id="footer_vendor""><?php echo Zend_Registry::get('vendor');?></p>
        <p id="footer_version">Snep <?php echo Zend_Registry::get('snep_version');?></p>
    </div>
</body>
</html>