<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/index.css" );
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/src/scriptaculous.js');
$this->headScript()->appendFile('/snep/includes/javascript/registrations.js');
echo $this->render('filter.phtml');
?>
<?php if(!$this->all_writable): ?>
<div class="error_box">
    <p><?php echo $this->translate("Error: The following files are not writable by the system:"); ?></p>
    <ul>
        <?php
        foreach ($this->writable_files as $file => $status) {
            echo "<li>$file</li>";
        }
        ?>
    </ul>
</div>
<?php endif; ?>
<table>
   <thead>
      <tr>
         <th> <?php echo $this->translate('Extension') ?> </th>
         <th> <?php echo $this->translate('Caller ID') ?> </th>
         <th> <?php echo $this->translate('Channel') ?> </th>
         <th> <?php echo $this->translate('Extension Group') ?> </th>
         <th colspan="3" class="action"> <?php echo $this->translate('Actions') ?>  </th>
      </tr>
   </thead>
   <tbody>
    <?php
    $c = 0;
    foreach($this->extensions as $cha => $val ): ?>
        <?php ($c ? $c = 0 : $c = 1 ); ?>
        <tr class="c<?php echo $c ?>">
            <td> <b> <?php echo $val['exten'] ?> </b> </td>
            <td> <?php echo $val['name'] ?> </td>
            <td> <?php echo $val['channel'] ?> </td>
            <td> <?php echo $val['group'] ?> </td>
            <td class="action">
                <a class="alterar"  href='<?php echo $this->url ?>/edit/id/<?php echo $val['exten'] ?>'>
                    <?php echo $this->translate('Edit')?>
                </a>
            </td>
            <td class="action">
                <?php if($val['exten'] != "admin"): ?>
                <span class="excluir" onclick="remove_item('<?php echo $this->url ?>/delete/id/<?php echo $val['exten'] ?>', '<?php echo $this->translate('Deseja realmente excluir o ramal?')?>' );">
                    <?php echo $this->translate('Delete')?>
                </span>
                <?php endif; ?>
            </td>
            <td class="action">
                <a class="membros"  href='<?php echo $this->baseUrl(); ?>/index.php/permission/<?php echo $val['exten']?>' >
                    <?php echo $this->translate('Permissions')?>
                </a>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<?php echo $this->render('pagination.phtml') ?>
