<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/system_status.css");
?>
<div class="snep_form" style="padding-top:10px;">

    <?php if ($this->error) : ?>
        <div class="error_box" >
            <?php echo $this->translate("Errors were detected in the configuration of SNEP, click "); ?>
            <a href="<?php echo $this->inspector; ?>">
                <?php echo $this->translate("here"); ?>
            </a>
            <?php echo $this->translate(" for more information"); ?>
        </div>
    <?php endif ?>
</div>


<table id="columns">
    <tr>
        <td width="50%">
            <div class="status_block">
                <h2>
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/server_status_icon.png">
                    <?php echo $this->translate("System Information"); ?>
                </h2>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Distribution"); ?></th>
                        <td> <?php echo $this->indexData["linux_ver"]; ?></td>
                    </tr>
                </table>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Kernel"); ?></th>
                        <td> <?php echo $this->indexData['linux_kernel']; ?></td>
                    </tr>
                </table>

                <table>
                    <tr>
                        <th><?php echo $this->translate("CPU"); ?></th>
                        <td> <?php echo $this->indexData["hardware"]; ?></td>
                    </tr>
                </table>

                <table>
                    <tr>
                        <th><?php echo $this->translate("CPU Usage"); ?></th>
                         <td>
                            <div class="bar_chart">
                                <?php 
                                $classColor = '';
                                if ($this->indexData["usage"] <= 33){
                                    $classColor = "bar_color_green";
                                }
                                else if ($this->indexData["usage"] >= 33 && $this->indexData["usage"] <= 66){
                                    $classColor = "bar_color_yellow";
                                }
                                else{
                                    $classColor = "bar_color_red ";
                                }
                                ?>
                                <div class="bar_inner <?php echo $classColor; ?>"  style="width:  <?php echo ($this->indexData["usage"]>100)?(100):($this->indexData["usage"]) . '%'; ?>;">
                                    <div class="bar_text">
                                        <?php echo $this->indexData["usage"] . '%'; ?>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Uptime"); ?></th>
                        <td> <?php echo $this->indexData["uptime"]; ?></td>
                    </tr>
                </table>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Asterisk"); ?></th>
                        <td> <?php echo $this->indexData["asterisk"]; ?></td>
                    </tr>
                </table>

                <table>
                    <tr>
                        <th><?php echo $this->translate("MySQL"); ?></th>
                        <td> <?php echo $this->indexData["mysql"]; ?></td>
                    </tr>
                </table>
                
                   <table>
                    <tr>
                        <th><?php echo $this->translate("Network Devices"); ?></th>
                        
                         <?php 
                       
                               
                                foreach ($this->indexData["net"] as $board) {
                                    echo '<td>';       
                                    echo ' <div class="bar_chart">';
                                                                
                                $classColor = '';
                                if ($board['up'] == 'up'){
                                    $classColor = "bar_color_green";
                                }
                                else if ($board['up'] == 'down'){
                                    $classColor = "bar_color_red";
                                }
                                else{
                                    $classColor = "bar_color_yellow ";
                                }
                                ?>
                                <div class="bar_inner <?php echo $classColor; ?>"  style="width: 100%;">
                                    <div class="bar_text">
                                        <?php echo $board['device']; ?>
                                    </div>
                                </div>
                            </div>
                        </td>
                        <?php } ?>
                    </tr>
                </table>

            </div>
            <div class="status_block">
                <h2>
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/modules_icon.png">
                    <?php echo $this->translate("Modules"); ?>
                </h2>
                <?php
                if (count($this->indexData["modules"]) > 0) {
                    foreach ($this->indexData["modules"] as $key => $value) {
                        ?>
                        <table>
                            <tr>
                                <th><?php echo $this->translate($value['name']); ?></th>
                                <td> <?php echo $this->translate($value['version']); ?></td>
                                <td> <?php echo $this->translate($value['description']); ?></td>
                            </tr>
                        </table>
                        <?php
                    }
                } else {
                    ?>
                    <p><?php echo $this->translate("No modules instaled."); ?></p>
                <?php } ?>
            </div>
        </td>
        <td>
            <div class="status_block">
                <h2>
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/stats_icon.png">
                    <?php echo $this->translate("PBX Statistics"); ?>
                </h2>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Registered Extensions"); ?></th>
                        <td> <?php echo $this->indexData["num_peers"]; ?></td>
                    </tr>
                </table>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Registered Trunks"); ?></th>
                        <td> <?php echo $this->indexData["num_trunks"]; ?></td>
                    </tr>
                </table>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Routes"); ?></th>
                        <td> <?php echo $this->indexData["num_routes"]; ?></td>
                    </tr>
                </table>
            </div>
            <div class="status_hard_block">
                <h2><img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/memory_icon.png"><?php echo $this->translate("Memory Usage"); ?></h2>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Type"); ?></th>
                        <th><?php echo $this->translate("Total"); ?></th>
                        <th><?php echo $this->translate("Free"); ?></th>
                        <th><?php echo $this->translate("Used"); ?></th>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate("Fisical Memory"); ?></th>
                        <td><?php echo $this->indexData["memory"]['ram']["total"]; ?></td>
                        <td><?php echo $this->indexData["memory"]['ram']["free"]; ?></td>
                        <td>
                            <div class="bar_chart">
                                <?php 
                                $classColor = '';
                                if ($this->indexData["memory"]['ram']["percent"] <= 33){
                                    $classColor = "bar_color_green";
                                }
                                else if ($this->indexData["memory"]['ram']["percent"] >= 33 && $this->indexData["memory"]['ram']["percent"] <= 66){
                                    $classColor = "bar_color_yellow";
                                }
                                else{
                                    $classColor = "bar_color_red ";
                                }
                                ?>
                                <div class="bar_inner <?php echo $classColor; ?>"  style="width:  <?php echo $this->indexData["memory"]['ram']["percent"] . '%'; ?>;">
                                    <div class="bar_text">
                                        <?php echo $this->indexData["memory"]['ram']["percent"] . '%'; ?>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate("Swap Memory"); ?></th>
                        <td><?php echo $this->indexData["memory"]['swap']["total"]; ?></td>
                        <td><?php echo $this->indexData["memory"]['swap']["free"] ; ?></td>
                        <td>
                         <div class="bar_chart">
                                <?php 
                                $classColor = '';
                                if ($this->indexData["memory"]['swap']["percent"] <= 33){
                                    $classColor = "bar_color_green";
                                }
                                else if ($this->indexData["memory"]['swap']["percent"] >= 33 && $this->indexData["memory"]['swap']["percent"] <= 66){
                                    $classColor = "bar_color_yellow";
                                }
                                else{
                                    $classColor = "bar_color_red ";
                                }
                                ?>
                                <div class="bar_inner <?php echo $classColor; ?>"  style="width: <?php echo $this->indexData["memory"]['swap']["percent"]. '%'; ?>;">
                                    <div class="bar_text">
                                        <?php echo $this->indexData["memory"]['swap']["percent"] . '%'; ?>
                                    </div>
                                </div>
                            </div>
                          </td>
                    </tr>
                </table>
            </div>
            <div class="status_hard_block">
                <h2>
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/storage_icon.png">
                    <?php echo $this->translate("Disk Usage"); ?>
                </h2>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Partition"); ?></th>
                        <th><?php echo $this->translate("Size"); ?></th>
                        <th><?php echo $this->translate("Free"); ?></th>
                        <th><?php echo $this->translate("Used"); ?></th>
                    </tr>
                    <?php
                    foreach ($this->indexData["space"] as $key => $value) {
                        ?>             

                        <tr>
                            <th><?php echo $value["mount_point"]; ?></th>
                            <td><?php echo $value["size"]; ?></td>
                            <td><?php echo $value["free"]; ?></td>
                             <td>
                         <div class="bar_chart">
                                <?php 
                                $classColor = '';
                                if ($value["percent"] <= 33){
                                    $classColor = "bar_color_green";
                                }
                                else if ($value["percent"] >= 33 && $value["percent"] <= 66){
                                    $classColor = "bar_color_yellow";
                                }
                                else{
                                    $classColor = "bar_color_red ";
                                }
                                ?>
                                <div class="bar_inner <?php echo $classColor; ?>"  style="width: <?php echo $value["percent"].'%'; ?>;">
                                    <div class="bar_text">
                                        <?php echo $value["percent"].'%'; ?>
                                    </div>
                                </div>
                            </div>
                          </td>
                        </tr> 

                    <?php } ?>
                </table>
            </div>
        </td>
    </tr>
</table>

