<?php echo $this->form; ?>
<script language="javascript" type="text/javascript">
    <?php echo $this->rule_actions; ?>

    var group_list = <?php echo $this->group_list; ?>;
    var alias_list = <?php echo $this->alias_list; ?>;
    var trunk_list = <?php echo $this->trunk_list; ?>;
    var contacts_group_list = <?php echo $this->contact_groups_list; ?>;

    var str_any = "<?php echo $this->translate("Any"); ?>";
    var str_regex = "<?php echo $this->translate("Regular Expression"); ?>";
    var str_group = "<?php echo $this->translate("Extension Group"); ?>";
    var str_contacts_group = "<?php echo $this->translate("Contact Group"); ?>";

    var str_ramal = "<?php echo $this->translate("Extension"); ?>";
    var str_trunk = "<?php echo $this->translate("Trunk"); ?>";
    var str_s     = "<?php echo $this->translate("No Destiny"); ?>";
    var str_alias = "<?php echo $this->translate("Expression Alias"); ?>";

    window.onload = function() {
        origObj = new MultiWx('orig', SrcField);        
        <?php echo $this->dt_agirules["src"]; ?>
        origObj.render();

        dstObj = new MultiWx('dst', DstField);
        <?php echo $this->dt_agirules["dst"]; ?>
        dstObj.render();

        timeObj = new MultiWx('time', TimeField);
        <?php echo $this->dt_agirules["time"]; ?>
        timeObj.render();
    }

    function atualizaValues() {
        $('srcValue').value  = origObj.getValue();
        $('dstValue').value  = dstObj.getValue();
        $('timeValue').value = timeObj.getValue();
    }

    Event.observe($('routeForm'), 'submit', atualizaValues);
</script>
