<?php echo $this->form; ?>
<script language="javascript" type="text/javascript">
    <?php echo $this->rule_actions; ?>

    var group_list = new Array(new Array("all","Todos"),new Array("administrator","administrator"),new Array("users","Usuarios"));
    var alias_list = new Array(new Array("1","Fixo Local"),new Array("2","Celular Local - VC1"),new Array("3","Fixo DDD"),new Array("4","Celular Interurbano - VC2/VC3"));
    var trunk_list = new Array(new Array("2","OpenS"),new Array("3","OpenS remoto"),new Array("4","Smyrno"));
    var contacts_group_list = new Array(new Array("1","Default"),new Array("2","Desenvolvimento"),new Array("3","Suporte"));

    var orig = new Array();
    var dst = new Array();

    var str_any = "<?php echo $this->translate("Qualquer"); ?>";
    var str_regex = "<?php echo $this->translate("Expressão Regular"); ?>";
    var str_group = "<?php echo $this->translate("Grupo"); ?>";
    var str_contacts_group = "<?php echo $this->translate("Grupo de Contatos"); ?>";

    var str_ramal = "<?php echo $this->translate("Ramal"); ?>";
    var str_trunk = "<?php echo $this->translate("Tronco"); ?>";
    var str_s     = "<?php echo $this->translate("Sem Destino"); ?>";

    window.onload = function() {
        origObj = new MultiWx('orig', SrcField);        
        <?php echo $this->dt_agirules["src"]; ?>
        origObj.render();

        dstObj = new MultiWx('dst', DstField);
        <?php echo $this->dt_agirules["dst"]; ?>
        dstObj.render();

        timeObj = new MultiWx('time', TimeField);
        <?php echo $this->dt_agirules["time"]; ?>
        timeObj.render();
    }

    function atualizaValues() {
        $('srcValue').value  = origObj.getValue();
        $('dstValue').value  = dstObj.getValue();
        $('timeValue').value = timeObj.getValue();
    }

    Event.observe($('routeForm'), 'submit', atualizaValues);
</script>
