<?php
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile('/snep/includes/javascript/enableField.js');
echo $this->form;

?>
<script type="text/javascript">
    techHighlight = function() {
        $('technology-type').childElements().each(function(el){
            $$("." + el.value).each(function(el){el.hide()});
        });
        $$("." + $('technology-type').value).each(function(el){el.show()});
    }
    Event.observe($('technology-type'), 'change', techHighlight);
    Event.observe(window, 'load', techHighlight);
    
    $( 'advanced-tempo').observe ('click' , time);
    $( 'advanced-dtmf_dial').observe('click', dtmf)

    Event.observe(window, 'load', time);
    Event.observe(window, 'load', dtmf);

    function time() {
        enableField('advanced-tempo', 'advanced-time_total');
        enableField('advanced-tempo', 'advanced-time_chargeby-Y');
        enableField('advanced-tempo', 'advanced-time_chargeby-M');
        enableField('advanced-tempo', 'advanced-time_chargeby-D');
    }
    function dtmf() {
        enableField('advanced-dtmf_dial', 'advanced-dtmf_dial_number');
    }
</script>