<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/main.css" );
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/add.css" );
$this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/functions_smarty.js');
$this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
?>
<div class="snep_form workaround ">
<?php if( $this->message ) : ?>
            <div class="error_box"> <?php echo $this->message  ?> </div>
<?php endif ?>


<form name="formulario"  method="POST" action="<?php echo $this->url . "/add/" ?>" >

<table cellspacing="0" align="center">
   <tr>
      <td valign="top">          
         <table class="subtable" style="width: 360px;">
            <tr>
                <td class="formlabel" width="140px" style="vertical-align:top;">
                    <label class="required"> <?php echo $this->translate("Carrier") ?> :</label>
                </td>
               <td class="subtable" >

                  <input type="hidden" name="data" id="data" value="<?php echo Zend_Date::now() ?>" />

                  <select name="operadora" id="operadora" style="width:220px;">
                     <?php if($this->carriers): ?>
                         <?php foreach ( $this->carriers as $idCarrier => $carrier ) : ?>
                            <?php if( isset($this->dados['operadora']) ) : ?>
                                <?php if( $idCarrier == $this->dados['operadora'] ) : ?>
                                    <option selected=selected value="<?php echo $idCarrier ?>"> <?php echo  $carrier ?>
                                 <?php else : ?>
                                    <option value="<?php echo $idCarrier ?>"> <?php echo  $carrier ?>
                               <?php  endif ?>
                            <?php else : ?>
                                    <option value="<?php echo $idCarrier ?>">  <?php echo $carrier ?>
                            <?php endif ?>
                         <?php endforeach ?>
                     <?php endif ?>
                  </select>
               </td>
            </tr>
            <tr>
               <td class="formlabel"  style="vertical-align:top;">
                   <label class="required"> <?php echo $this->translate("Country") ?>:</label>
               </td>
               <td class="subtable" >
                   <select id="pais" name="pais"  style="width:220px;">
                       <option value="BRASIL">BRASIL
                   </select>
               </td>
            </tr>
            <tr>
               <td class="formlabel"  style="vertical-align:top;">
                    <label class="required">  <?php echo $this->translate("State") ?>:</label>
               </td>
               <td class="subtable" >
                  <select onchange="cidades(this.value)" name="estado" id="estado"  style="width:220px;">
                     <?php if($this->states): ?>
                         <?php foreach ( $this->states as $idState => $state ) : ?>
                            <?php if( isset($this->dados['estado']) ) : ?>
                                <?php if( $idState == $this->dados['estado'] ) : ?>
                                    <option selected=selected value="<?php echo $idState ?>"> <?php echo  $state ?>
                                 <?php else : ?>
                                    <option value="<?php echo $idState ?>"> <?php echo $state ?>
                               <?php  endif ?>
                            <?php else : ?>
                                    <option value="<?php echo $idState ?>"> <?php echo $state ?>
                            <?php endif ?>
                         <?php endforeach ?>
                     <?php endif ?>
                  </select>             
                  <div class="waiting" id="wait_estado" style="display:none;">

                  </div>
               </td>
            </tr>
            <tr>
               <td class="formlabel"  style="vertical-align:top;">
               <label class="required">  <?php echo $this->translate("City") ?>:</label>
               </td>
               <td class="subtable" >
                    <select name="cidade" id="cidade"  style="width:220px;" >
                         <?php if( $this->cities ): ?>
                             <?php foreach ( $this->cities as $idCity => $city ) : ?>
                                <?php echo "<option value=\"$idCity\">" . $city; ?>
                             <?php endforeach ?>
                         <?php endif ?>
                    </select>
               </td>
            </tr>

            <tr>
               <td class="formlabel"  style="vertical-align:top;">
                     <label class="required">  <?php echo $this->translate("Country Code") ?>:</label>
               </td>
               <td class="subtable"  style="vertical-align:top;" >
                  <input name="ddi" id="ddi" type="text" size="5" maxlength="4" value="55" />
               </td>
            </tr>

            <tr>
               <td class="formlabel"  style="vertical-align:top;">
                     <label class="required">  <?php echo $this->translate("City Code") ?>:</label>
               </td>
               <td class="subtable" >
                  <input name="ddd" id="ddd" type="text" value="<?php echo ( isset($this->dados['ddd'] ) ?  $this->dados['ddd'] : "" ) ?>" size="5" maxlength="2" />
                  <?php if ( isset( $this->error['ddd'] ) ) :  ?>
                      <ul class="errors">
                          <li>
                            <?php echo $this->error['ddd']; ?>
                          </li>
                      </ul>
                  <?php endif ?>
               </td>
            </tr>

            <tr>
               <td class="formlabel"  style="vertical-align:top;">
                    <label class="required">  <?php echo $this->translate("Prefix") ?>:</label>
               </td>
               <td class="subtable" >
                  <input name="prefixo" id="prefixo" type="text" value="<?php echo ( isset($this->dados['prefixo'] ) ?  $this->dados['prefixo'] : "" ) ?>" size="5" maxlength="4" />
                  <?php if ( isset( $this->error['prefixo'] ) ) :  ?>
                       <ul class="errors">
                           <li>
                             <?php echo $this->error['prefixo']; ?>
                           </li>
                       </ul>
                  <?php endif ?>
               </td>
            </tr>
            <tr>
               <td class="formlabel"> <?php echo $this->translate("Minute Fee for Residencial") ?>:</td>
               <td class="subtable" >
                  <input name="vfix" id="vfix" class="campos" type="text" value="<?php echo ( isset($this->dados['vfix'] ) ?  $this->dados['vfix'] : "" ) ?>" size="5"  value="0"  style="text-align: right;" />
                  <small> <?php echo $this->translate("Use dot for decimal"); ?> </small>
               </td>
            </tr>
            <tr>
               <td class="formlabel"> <?php echo $this->translate("Minute Fee for Mobile") ?>:</td>
               <td class="subtable" >
                  <input name="vcel" id="vcel" class="campos" value="<?php echo ( isset($this->dados['vcel'] ) ?  $this->dados['vcel'] : "" ) ?>" type="text" size="5"  value="0" style="text-align: right;" />
                  <small> <?php echo $this->translate("Use dot for decimal"); ?> </small>
               </td>
            </tr>

         </table>
      </td>
      <td valign="top">
          <ul> <b> <?php echo $this->translate("General Rules");?></b>
            <li>
                <?php echo $this->translate("Os valores PADRÃO (fixo e celular) para cada Operadora é informado no cadastro da Operadora."); ?>
            </li>
            <li>
                <?php echo $this->translate("Para reajuste de uma tarifa PADRÃO existente, mantenha os campos com os seguintes dados:"); ?>
            </li>
            <li>
                <ul>
                    <li>
                        <strong><?php echo $this->translate('State'); ?>:</strong> <i>---</i>
                    </li>
                    <li>
                        <strong><?php echo $this->translate('City'); ?>:</strong> <i><?php echo $this->translate('Selecionar'); ?></i>
                    </li>
                    <li>
                        <strong><?php echo $this->translate('City Code'); ?>:</strong> <i> 0 </i>
                    </li>
                    <li>
                        <strong><?php echo $this->translate('Prefix'); ?>:</strong> <i>0000</i>
                    </li>
                </ul>
            </li>
            <li>
                <?php echo $this->translate("O cadastro de uma Tarifa obedece 3 regras:") ?>
                <ul>
                    <li>
                        1 - <?php echo $this->translate('Se determinadas cidades tem valor de tarifa diferenciado, independente do PREFIXO de destino, uma Tarifa Individual deverá ser cadastrada, atentando para informar corretamente o DDD da cidade e o PREFIXO');?>
                        <strong>'0000'</strong>
                    </li>
                    <li>
                        2 - <?php echo $this->translate('Se a Operadora tiver valor diferenciado para determinados PREFIXOS de uma mesma CIDADE, uma Tarifa Individual deverá ser cadastrada para cada PREFIXO');?>
                    </li>
                    <li>
                        3 - <?php echo $this->translate('Para');?>
                        <strong> <?php echo $this->translate('Tarifas INTERNACIONAIS');?>, </strong>
                        <?php echo $this->translate('uma Tarifa Individual deverá ser cadastrada para cada PAIS, atentando para os seguintes detalhes');?>:
                        <ul>
                            <li>
                               a) <?php echo $this->translate('Informar o Code'); ?>
                            </li>
                            <li>
                               b) <?php echo $this->translate('Informar o Code da Cidade'); ?> = 000
                            </li>
                            <li>
                               c) <?php echo $this->translate('Informar o PREFIXO') ?> = 0000
                            </li>
                        </ul>

                    </li>
                </ul>
            </li>
          </ul>

      </td>
   </tr>
</table>

<div class="menus">
    <div style="margin:0 auto; width: 200px;padding: 10px;">
         <input class="submit" type="submit" id="submit" value="<?php echo $this->translate("Salvar"); ?>">
         <a class="snep_form_cancel" href="<?php echo $this->url ?>"> <?php echo $this->translate('Cancel'); ?> </a>
    </div>
</div>

</form>
</div>

<script language="javascript" type="text/javascript">

 document.forms[0].elements[0].focus() ;

  function cidades(uf) {

        $('wait_estado').show();

        var url = '<?php echo $this->url?>/cidade/';
        var params = 'uf='+uf;
        var retorno = new Ajax.Request (
            url, {
                method: 'POST',
                parameters: params,
                onComplete: ret_cidade
            }
        );

  }

  function ret_cidade(ret) {
       $('cidade').innerHTML = "";
       $('cidade').insert(ret.responseText);
       $('wait_estado').hide();
  }

<?php 
if( isset($this->dados['estado'])) {
    echo "cidades('{$this->dados['estado']}');";
}
?>
  
</script>
