<?php
    $this->headLink()->appendStylesheet( $this->baseUrl() . "/css/add.css" );
    $this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
?>

<div class="snep_form workaround ">
<?php if( $this->message ) : ?>
            <div class="error_box"> <?php echo $this->message  ?> </div>
<?php endif ?>
           

<form name="formulario"  method="POST" action="<?php echo $this->url . "/edit/" ?>" >

<table cellspacing="0" align="center">
   <tr>
      <td valign="top" style="width:140px;">

         <input type="hidden" name="id" value="<?php echo $this->Carrier['codigo'] ?>" />
         
         <table class="subtable" style="width: 360px;">
            <tr>
               <td class="formlabel" width="140px"> <?php echo $this->translate("Carrier") ?> </td>
               <td class="subtable" >
                  <select name="operadora" disabled  style="width:220px;" >
                     <?php if($this->carriers): ?>
                         <?php foreach ( $this->carriers as $idCarrier => $_carrier ) : ?>
                            <?php if( $idCarrier == $this->Carrier['operadora'] ) : ?>
                                <?php echo "<option value=\"$idCarrier\">" . $_carrier; ?>
                            <?php endif ?>                            
                         <?php endforeach ?>
                     <?php endif ?>
                  </select>
               </td>
            </tr>
            <tr>
               <td class="formlabel"> <?php echo $this->translate("Country") ?>:</td>
               <td class="subtable" >
                  <select id="pais" name="pais" disabled  style="width:220px;" >
                       <option value="<?php echo $this->Carrier['pais'] ?>"><?php echo $this->Carrier['pais'] ?>
                   </select>
               </td>
            </tr>
            <tr>
               <td class="formlabel"> <?php echo $this->translate("State") ?>:</td>
               <td class="subtable" >
                  <select disabled onchange="cidades(this.value)" name="estado"  style="width:220px;">
                      <option value="<?php echo $this->billingState['cod'] ?>"> <?php echo $this->billingState['name'] ?>
                  </select>
                  <div class="waiting" id="wait_estado" style="display:none;">

                  </div>
               </td>
            </tr>
            <tr>
               <td class="formlabel"> <?php echo $this->translate("City") ?>:</td>
               <td class="subtable" >
                    <select name="cidade" id="cidade" disabled  style="width:220px;">
                        <option value="<?php echo $this->Carrier['cidade']?>">  <?php echo $this->Carrier['cidade']?>
                    </select>
               </td>
            </tr>

            <tr>
               <td class="formlabel"> <?php echo $this->translate("Country Code") ?> :</td>
               <td class="subtable" >
                  <input name="ddi" type="text" disabled size="5" maxlength="4" value="<?php echo $this->Carrier['ddi']?>" />
               </td>
            </tr>

            <tr>
               <td class="formlabel"> <?php echo $this->translate("City Code") ?> :</td>
               <td class="subtable" >
                  <input name="ddd" id="ddd" disabled type="text" size="5" maxlength="3" value="<?php echo $this->Carrier['ddd']?>" />
               </td>
            </tr>

            <tr>
               <td class="formlabel"> <?php echo $this->translate("Prefix") ?> :</td>
               <td class="subtable" >
                  <input name="prefixo" disabled id="prefixo" type="text" size="5" maxlength="4" value="<?php echo $this->Carrier['prefixo']?>" />
               </td>
            </tr>
            <tr>
               <td colspan="4" >
                    <div class="info_box"> <?php echo $this->translate("Warning: Changes to existing fees, influence on the report.") ?>  </div>
               </td>
            </tr>

         </table>
      </td>

      <td valign="top">
          <table id="billList" style="border-collapse: separate;">
           <thead>
              <tr>
                 <td class="cen" width="30%"> <?php echo $this->translate('Starts from') ?> </td>
                 <td class="dir"> <?php echo $this->translate('Minute Fee for Residencial') ?> </td>
                 <td class="dir"> <?php echo $this->translate('Minute Fee for Mobile') ?> </td>
                 <td class="cen" width="15%"> <?php echo $this->translate('Actions') ?> </td>
              </tr>
           </thead>

           <?php
           $cnt = 0;
           $c = 0;           
           foreach($this->billingValues as $idBill => $bill) : ?>
               <?php ($c ? $c = 0 : $c = 1 ); ?>
                 <tr  class="c<?php echo $c ?>">
                     <input type="hidden" name="data[<?php echo $idBill ?>]" id="data" value="<?php echo $bill['data'] ?>" />
                     <td class="numeric">
                        <?php echo new Zend_Date($bill['data']); ?>
                     </td>
                     <td class="dir">
                        <input type="text" name="vfix[<?php echo $idBill ?>]" id="vfix" value="<?php echo $bill['vfix'] ?>"  class="campos" style="text-align:right;"  size="8"  onChange="this.form.elements['action[{$key}]'].checked=true;;" />
                     </td>
                     <td class="dir">
                        <input type="text" name="vcel[<?php echo $idBill ?>]" id="vcel" value="<?php echo $bill['vcel'] ?>" class="campos" style="text-align:right;" size="8" onChange="this.form.elements['action[{$key}]'].checked=true;;"/>
                     </td>
                     <td class="txt_alterar">
                         <input class="campos" type="checkbox" name="action[<?php echo $idBill ?>]" value="<?php echo $idBill ?>" />
                         <?php echo $this->translate('Edit') ?>
                     </td>
                 </tr>
           <?php
           $cnt = $idBill;
           
           endforeach ?>

           <?php $cnt++ ?>
         
           <tr>
              <td colspan="6" height="30">
                <span class="include"> <?php echo $this->translate('New Adjustment'); ?> </span>
              </td>
           </tr> 
           <input type="hidden" name="data[<?php echo $cnt ?>]" id="data" value="<?php echo Zend_Date::now() ?>" />

           <tr bgcolor="#FFF9C4">
              <td class="cen"> <?php echo new Zend_Date(); ?> </td>
              <td class="dir">
                 <input type="text" name="vfix[<?php echo $cnt ?>]" id="vfix" class="campos" style="text-align:right;"  size="8" value="0"   onChange="this.form.elements['action[<?php echo $cnt ?>]'].checked=true;;" />
              </td>
              <td class="dir">
                 <input type="text" name="vcel[<?php echo $cnt ?>]" id="vcel" class="campos" style="text-align:right;" size="8" value="0"  onChange="this.form.elements['action[<?php echo $cnt ?>]'].checked=true;;"/>
              </td>
              <td class="txt_alterar">
                  <input class="campos" type="checkbox" name="action[<?php echo $cnt ?>]" value="<?php echo $cnt ?>" />
                  <?php echo $this->translate('Add'); ?>
              </td>
           </tr>
        </table>

      </td>
   </tr>
</table>

<div class="menus">
    <div style="margin:0 auto; width: 200px;padding: 10px;">
         <input class="submit" type="submit" id="submit" value="<?php echo $this->translate("Salvar"); ?>">
         <a class="snep_form_cancel" href="<?php echo $this->url ?>"> <?php echo $this->translate('Cancel'); ?> </a>
    </div>
</div>

</form>
</div>

<script language="javascript" type="text/javascript">

 document.forms[0].elements[0].focus() ;

 function check_form(acao) {
    campos = new Array() ;
    campos[0] = "{$LANG.city};"+document.formulario.cidade.value+";NOT_NULL;";
    campos[1] = "{$LANG.ddi};"+document.formulario.ddi.value+";NUM;";
    campos[2] = "{$LANG.ddd};"+document.formulario.ddd.value+";NUM;";
    campos[3] = "{$LANG.prefix};"+document.formulario.prefixo.value+";NOT_NULL;";
    campos[4] = "{$LANG.operadora};"+document.formulario.operadora.value+";NOT_NULL;";
    if (acao != "grava_alterar") {
       campos[5]="{$LANG.vlrbase_fix};"+document.formulario.vfix.value+";FLOAT;";
       campos[6]="{$LANG.vlrbase_cel};"+document.formulario.vcel.value+";FLOAT;";
    } else {
       var ctd = 5 ;
       var lst = document.formulario.action ;
       for(var x=0 ; x<lst.length ; x++){
          var ind = lst[x].value ;
          var avfix = document.formulario.elements['vfix['+ind+']'] ;
          var avcel = document.formulario.elements['vcel['+ind+']'] ;
          if (lst.checked) {
             // Verifica Name nao esta em Branco
             dados[ctd] = "{$LANG.vlrbase_fix};"+avfix.value+";FLOAT;";
             ctd += 1;
             // Verifica senha numerica
             dados[ctd] = "{$LANG.vlrbase_cel};"+avcel.value+";FLOAT;";
             ctd += 1 ;
          }
       }
    }

    return valida_formulario(campos) ;

 }


</script>

<script language="javascript" type="text/javascript">

   function cidades(uf) {

       $('wait_estado').show();

        var url = '<?php echo $this->url?>/cidade/';
        var params = 'uf='+uf;
        var retorno = new Ajax.Request (
            url, {
                method: 'POST',
                parameters: params,
                onComplete: ret_cidade
            }
        );

   }

   function ret_cidade(ret) {
       $('cidade').innerHTML = "";
       $('cidade').insert(ret.responseText);
       $('wait_estado').hide();
   }

   function prefixo(cidade) {

       var url = 'rel_prefixo.php';
       var params = 'cidade='+cidade;
       var retorno = new Ajax.Request (
           url, {
                method: 'POST',
                parameters: params,
                onComplete: ret_prefixo
           }
       );
   }

   function ret_prefixo(ret) {

       alert(ret.responseText);
       $('ddd').value = ret.responseText;
   }

</script>