<div class="phone-list">
     <dt id="nameCont-label" style="vertical-align: top;">
         <label for="nameCont" class="required">Telefones</label>
     </dt>
     <dd class="quadro">
        <ol id="phones">
            <!--
            <li id="phone_0">
                <input type="text" name="phones[]"  />
                <img src="/snep/imagens/delete.png"  onclick="remover(0)" />
            </li>
            -->
            
        </ol>         
         <input type="button" class="new_button ml5" value="Adicionar Número" onclick="newphone();" />
     </dd>
</div>


