<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/index.css" );
$this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/scriptaculous/src/scriptaculous.js');
$this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/removeItem.js');

echo $this->render('filter.phtml');

if( $this->error['error'] ) : ?>
    <div class="error_box"> <?php echo $this->error['message']  ?> </div>
<?php endif ?>

<table>
   <thead>
      <tr>
         <!-- <th> <?php echo $this->translate('Áudio') ?> </th> -->
         <th> <?php echo $this->translate('Filename') ?> </th>
         <th> <?php echo $this->translate('Description') ?> </th>
         <th class="numeric"> <?php echo $this->translate('File') ?> </th>
         <th class="numeric"> <?php echo $this->translate('Backup') ?> </th>
         <th colspan="4" class="action"> <?php echo $this->translate('Actions') ?> </th>
      </tr>
   </thead>   
   <tbody>
    <?php
    $c = 0;
    if($this->files):
        foreach($this->files as $file ): ?>
            <?php ($c ? $c = 0 : $c = 1 ); ?>
            <tr class="c<?php echo $c ?>">
                <td> 
                    <b> <?php echo $file['arquivo'] ?> </b>
                </td>
                <td> 
                    <?php echo $file['descricao'] ?>
                </td>
                <td class="action">
                    <?php $fullpath = ( isset( $file['fullpath'] ) ? $file['fullpath']  :  false ); ?>
                    <?php if( $fullpath ) : ?>
                        <a class="arquivo" href="<?php echo $fullpath ?>"></a>
                    <?php endif ?>
                </td>
                <td class="action">
                    <?php $fullpath = ( isset( $file['backuppath'] ) ? $file['backuppath']  :  false ); ?>
                    <?php if( $fullpath ) : ?>
                        <a class="arquivo" href="<?php echo $fullpath ?>"></a>
                    <?php endif ?>
                </td>
                <td class="action">
                    <?php if( isset( $file['backuppath'] ) ) : ?>
                        <a class="backup" href="<?php echo $this->url ?>/restore/file/<?php echo $file['arquivo'] ?>">
                            <?php echo $this->translate('Restore')?>
                        </a>
                    <?php endif ?>
                </td>
                <td class="action">
                    <a class="alterar" href="<?php echo $this->url ?>/edit/file/<?php echo $file['arquivo'] ?>">
                        <?php echo $this->translate('Edit')?>
                    </a>
                </td>
                <td class="action">
                    <?php $this->remove_msg = $this->translate("Are you sure you want to delete this item?");?>
                    <span class="excluir" onclick="remove_item('<?php echo $this->url ?>','<?php echo $file['arquivo'] ?>','<?php echo $this->remove_msg ?>')">
                        <?php echo $this->translate('Delete')?>
                    </span>
                </td>
            </tr>
        <?php endforeach ?>
    <?php endif ?>
</table>

<?php echo $this->render('pagination.phtml') ?>