<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/index.css" );
?>
<?php if($this->error): ?>
    <div class="error_box">
        <?php echo $this->error; ?>
    </div>
<?php endif ?>

<?php if($this->invalid): ?>

<div style="text-align:center;">
    <h2><?php echo $this->translate("Invalid File") ?></h2>
    <button type="button" onClick="history.back();"><?php echo $this->translate("Back"); ?></button>
</div>

<?php else: ?>

<form name="formulario" method="POST" action="<?php echo $this->url ?>/csvprocess" >
    <table width="100%">
        <thead>
            <tr>
                <?php
                $csvarq = $this->csvprocess;
                foreach ( $csvarq[0] as $ind => $linha ) :
                ?>
                    <th>
                        <select name="field[<?php echo $ind ?>]">
                        <?php foreach ($this->fields as $field => $name) : ?>
                            <option value="<?php echo $field; ?>"><?php echo $name; ?></option>
                        <?php endforeach ?>
                        </select>
                    </th>
                <?php endforeach ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($csvarq as $ind => $linha) : ?>
            <tr>
                <?php foreach ($linha as $item) : ?>
                <td><?php echo $item ?></td>
                <?php endforeach ?>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>

    <div id="main_container" style="border-top: none;">
        <p style="text-align: center; margin: 0px; padding: 5px;">
            <label for="group"><?php echo $this->translate("Group"); ?></label>
            
            <select id="group" name="group" class="campos">
                <?php if( isset( $this->group ) )  : ?>
                    <?php foreach ($this->group as $id => $group) : ?>
                            <option value='<?php echo $id ?>'> <?php echo $group ?> </option>
                    <?php endforeach ?>
                <?php endif ?>
            </select>

            <br />

            <input type="checkbox" name="discard_first_row" id="discard_first_row" /><label for="discard_first_row"><?php echo $this->translate("Discard header"); ?></label><br />
            <input class="new_button" <?php echo ( isset($this->error) ? 'disabled="true"' : null ) ?> type="submit" id="salvar" value="<?php echo $this->translate("Save"); ?>" />
            <input class="new_button" type="button" id="voltar" value="<?php echo $this->translate("Cancel"); ?>" onClick="history.back()" />
        </p>
    </div>
</form>
<?php endif; ?>