<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/modules/default/css/index.css" );
$this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/removeItem.js');
$this->headScript()->appendFile( $this->baseUrl() . '/includes/javascript/selectBox.js');
echo $this->render('filter.phtml');
?>
<table>
   <thead>
      <tr>
         <th class="numeric"> <?php echo $this->translate('Code') ?> </th>
         <th> <?php echo $this->translate('Name') ?> </th>
         <th> <?php echo $this->translate('Group') ?> </th>
         <th> <?php echo $this->translate('City') ?> </th>
         <th> <?php echo $this->translate('State') ?> </th>
         <th> <?php echo $this->translate('Zip Code') ?> </th>
         <th class="numeric"> <?php echo $this->translate('Phone') ?> </th>
         <th class="numeric"> <?php echo $this->translate('Cellphone') ?> </th>
         <th colspan="2" class="action"> <?php echo $this->translate('Actions') ?> </th>
      </tr>
   </thead>
   <tbody>
    <?php
    $c = 0;
    if($this->contacts):
        foreach($this->contacts as $contact ): ?>
            <?php ($c ? $c = 0 : $c = 1 ); ?>
            <tr class="c<?php echo $c ?>">
                <td class="numeric"> <b> <?php echo $contact['id'] ?> </b> </td>
                
                <td> <?php echo $contact['name'] ?> </td>
                <td> <?php echo $contact['group'] ?> </td>
                <td> <?php echo $contact['city'] ?> </td>
                <td> <?php echo $contact['state'] ?> </td>
                <td> <?php echo $contact['cep'] ?> </td>
                <td class="numeric"> 
                    <?php echo $contact['phone'] ?>
                </td>
                <td class="numeric"> 
                    <?php echo $contact['cellphone'] ?>
                </td>
                <td class="action">
                    <a class="alterar" href="<?php echo $this->url ?>/edit/id/<?php echo $contact['id'] ?>">
                        <?php echo $this->translate('Edit')?>
                    </a>
                </td>
                
                <td class="action" class="display:inline;">
                    <?php $this->remove_msg = $this->translate("Do you really wish to remove this item?");?>
                    <span class="excluir" onclick="remove_item('<?php echo $this->url ?>','<?php echo $contact['id'] ?>','<?php echo $this->remove_msg ?>')">
                        <?php echo $this->translate('Delete')?>
                    </span>
                </td>
                
            </tr>
        <?php endforeach ?>
    <?php endif ?>
</table>

<?php echo $this->render('pagination.phtml') ?>