<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/system_status.css");
?>

<table id="columns">
    <tr>
        <td width="50%">
            <div class="status_block">
                <h2>
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/server_status_icon.png">
                    <?php echo $this->translate("Server Status"); ?>
                </h2>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Distribution"); ?></th>
                        <td>Windows 3.11 for Workgroups</td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate("Kernel"); ?></th>
                        <td>2.6.38-rc8-smp</td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate("CPU"); ?></th>
                        <td>Intel(R) Core(TM) i5 CPU M 480  @ 2.67GHz</td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate("Uptime"); ?></th>
                        <td><?php echo $this->translate("%d days %s:%s:%s", 4, 12,15,07); ?></td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate("Asterisk"); ?></th>
                        <td>1.4.36</td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate("MySQL"); ?></th>
                        <td>Ver 14.14 Distrib 5.1.55</td>
                    </tr>
                </table>
            </div>
            <div class="status_block">
                <h2>
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/modules_icon.png">
                    <?php echo $this->translate("Modules"); ?>
                </h2>

                <p>No modules, cabron!</p>
            </div>
        </td>
        <td>
            <div class="status_block">
                <h2>
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/stats_icon.png">
                    <?php echo $this->translate("PBX Statistics"); ?>
                </h2>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Distribution"); ?></th>
                        <td>Windows 3.11 for Workgroups</td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate("Kernel"); ?></th>
                        <td>2.6.38-rc8-smp</td>
                    </tr>
                </table>
            </div>
            <div class="status_block">
                <h2><img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/memory_icon.png"><?php echo $this->translate("Memory Usage"); ?></h2>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Distribution"); ?></th>
                        <td>Windows 3.11 for Workgroups</td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate("Kernel"); ?></th>
                        <td>2.6.38-rc8-smp</td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate("Kernel"); ?></th>
                        <td>2.6.38-rc8-smp</td>
                    </tr>
                </table>
            </div>
            <div class="status_block">
                <h2>
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/storage_icon.png">
                    <?php echo $this->translate("Disk Usage"); ?>
                </h2>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Distribution"); ?></th>
                        <td>Windows 3.11 for Workgroups</td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate("Kernel"); ?></th>
                        <td>2.6.38-rc8-smp</td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate("Kernel"); ?></th>
                        <td>2.6.38-rc8-smp</td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate("Kernel"); ?></th>
                        <td>2.6.38-rc8-smp</td>
                    </tr>
                </table>
            </div>
        </td>
    </tr>
</table>

