<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/system_status.css");
?>
<div class="snep_form">
    <p style="text-align:center;">
        <strong style="color: red;"><?php echo $this->translate("ATTENTION"); ?>:</strong>
        <?php echo $this->translate("This software is in Alpha stage. Its unstable and may contain defects."); ?>
    </p>

    <?php if( $this->error  ) : ?>
            <div class="error_box" >
                <?php echo $this->translate("Errors were detected in the configuration of SNEP, click ");  ?>
                <a href="<?php echo $this->inspector; ?>">
                    <?php echo $this->translate("here"); ?>
                </a>
                    <?php echo $this->translate(" for more information"); ?>
            </div>
    <?php endif ?>
</div>


<table id="columns">
    <tr>
        <td width="50%">
            <div class="status_block">
                <h2>
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/server_status_icon.png">
                    <?php echo $this->translate("System Information"); ?>
                </h2>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Distribution"); ?></th>
                        <td> <?php echo $this->indexData["linux_ver"]; ?></td>
                    </tr>
                </table>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Kernel"); ?></th>
                        <td> <?php echo $this->indexData['linux_kernel']; ?></td>
                    </tr>
                </table>

                <table>
                    <tr>
                        <th><?php echo $this->translate("CPU"); ?></th>
                        <td> <?php echo $this->indexData["hardware"]; ?></td>
                    </tr>
                </table>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Turn-on Time"); ?></th>
                        <td> <?php echo $this->indexData["uptime"]; ?></td>
                    </tr>
                </table>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Asterisk"); ?></th>
                        <td> <?php echo $this->indexData["asterisk"]; ?></td>
                    </tr>
                </table>

                <table>
                    <tr>
                        <th><?php echo $this->translate("MySQL"); ?></th>
                        <td> <?php echo $this->indexData["mysql"]; ?></td>
                    </tr>
                </table>

            </div>
            <div class="status_block">
                <h2>
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/modules_icon.png">
                    <?php echo $this->translate("Modules"); ?>
                </h2>
                <?php
                if (count($this->indexData["modules"]) > 0) {
                    foreach ($this->indexData["modules"] as $key => $value) {
                        ?>
                        <table>
                            <tr>
                                <th><?php echo $value['name']; ?></th>
                                <td> <?php echo $value['version']; ?></td>
                                <td> <?php echo $value['description']; ?></td>
                            </tr>
                        </table>
                        <?php
                    }
                } else {
                    ?>
                    <p><?php echo $this->translate("No modules instaled."); ?></p>
                <?php } ?>
            </div>
        </td>
        <td>
            <div class="status_block">
                <h2>
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/stats_icon.png">
                    <?php echo $this->translate("PBX Statistics"); ?>
                </h2>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Registered Extensions"); ?></th>
                        <td> <?php echo $this->indexData["num_peers"]; ?></td>
                    </tr>
                </table>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Registered Trunks"); ?></th>
                        <td> <?php echo $this->indexData["num_trunks"]; ?></td>
                    </tr>
                </table>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Routes"); ?></th>
                        <td> <?php echo $this->indexData["num_routes"]; ?></td>
                    </tr>
                </table>
            </div>
            <div class="status_hard_block">
                <h2><img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/memory_icon.png"><?php echo $this->translate("Memory Usage"); ?></h2>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Type"); ?></th>
                        <th><?php echo $this->translate("Total"); ?></th>
                        <th><?php echo $this->translate("Free"); ?></th>
                        <th><?php echo $this->translate("Used"); ?></th>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate("Fisical Memory"); ?></th>
                        <td><?php echo sprintf("%.2f", ($this->indexData["memory"]['ram']["total"] / 1024)); ?></td>
                        <td><?php echo sprintf("%.2f", ($this->indexData["memory"]['ram']["free"] / 1024)); ?></td>
                        <td><?php echo $this->indexData["memory"]['ram']["percent"].'%'; ?></td>
                    </tr>
                    <tr>
                        <th><?php echo $this->translate("Swap Memory"); ?></th>
                        <td><?php echo sprintf("%.2f", ($this->indexData["memory"]['swap']["total"] / 1024)); ?></td>
                        <td><?php echo sprintf("%.2f", ($this->indexData["memory"]['swap']["free"] / 1024)); ?></td>
                        <td><?php echo $this->indexData["memory"]['swap']["percent"].'%'; ?></td>
                    </tr>
                </table>

            </div>
            <div class="status_hard_block">
                <h2>
                    <img alt="" src="<?php echo $this->baseUrl(); ?>/imagens/index/storage_icon.png">
                    <?php echo $this->translate("Disk Usage"); ?>
                </h2>

                <table>
                    <tr>
                        <th><?php echo $this->translate("Partition"); ?></th>
                        <th><?php echo $this->translate("Size"); ?></th>
                        <th><?php echo $this->translate("Free"); ?></th>
                        <th><?php echo $this->translate("Used"); ?></th>
                    </tr>
                    <?php  
                                    foreach ($this->indexData["space"] as $key => $value) {
                             ?>             
                                   
                 <tr>
                <th><?php echo $value["mount_point"]; ?></th>
                 <td><?php echo sprintf("%.2f",($value["size"]/1048576)); ?></td>
                 <td><?php echo sprintf("%.2f",($value["free"]/1048576)); ?></td>
                 <td><?php echo $value["percent"]; ?></td>
            </tr> 
            
             <?php } ?>
                </table>
            </div>
        </td>
    </tr>
</table>

