<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/index.css" );
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/src/scriptaculous.js');
$this->headScript()->appendFile('/snep/includes/javascript/registrations.js');
echo $this->render('filter.phtml') ?>

<table cellspacing="0" cellpadding="0" border="0" align="center" width="100%" >
   <thead>
      <tr>
         <th width="50"> <?php echo $this->translate('Código') ?> </th>
         <th> <?php echo $this->translate('Nome') ?> </th>
         <th colspan="2" class="action"> <?php echo $this->translate('Ações') ?> </th>
      </tr>
   </thead>
   <tbody>
    <?php
    $c = 0;
    if( count( $this->group ) > 0 ):
        foreach($this->group as $cha => $val ): ?>
            <?php ($c ? $c = 0 : $c = 1 ); ?>
            <tr class="c<?php echo $c ?>">
                <td> <b> <?php echo $val['id'] ?> </b> </td>
                <td> <?php echo $val['name'] ?> </td>
                <td class="action">
                    <a class="alterar" href='<?php echo $this->BaseUrl ?>/contactgroups/edit/id/<?php echo $val['id'] ?>'>
                        <?php echo $this->translate('Alterar') ?>
                    </a>
                </td>
                <td class="action">
                    <a class="excluir" href='<?php echo $this->BaseUrl ?>/contactgroups/del/id/<?php echo $val['id'] ?>'>
                        <?php echo $this->translate('Excluir')?>
                    </a>
                </td>
            </tr>
        <?php endforeach?>
    <?php endif ?>

</table>
<?php echo $this->render('pagination.phtml') ?>