<?php
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/src/scriptaculous.js');
$this->headScript()->appendFile('/snep/includes/javascript/registrations.js');
echo $this->render('filter.phtml')
?>

<table cellspacing="0" cellpadding="0" border="0" align="center" width="100%" >
   <thead>
      <tr>
         <td> <?php echo $this->translate('Código') ?> </td>
         <td> <?php echo $this->translate('Nome') ?> </td>
         <td> <?php echo $this->translate('Tipo') ?> </td>
         <td> <?php echo $this->translate('Descrição') ?> </td>
         <td colspan="2" class="action"> <?php echo $this->translate('Ações') ?>  </td>         
      </tr>
   </thead>
   <tbody>
    <?php
    $c = 0;
    foreach($this->costcenter as $id => $val ): ?>
        <?php ($c ? $c = 0 : $c = 1 ); ?>
        <tr class="c<?php echo $c ?>">
            <td> <b> <?php echo $val['codigo'] ?> </b> </td>
            <td> <?php echo $val['nome'] ?> </td>
            <td> <?php echo $val['tipo'] ?> </td>
            <td> <?php echo $val['descricao'] ?> </td>
            <td class="action">
                <a class="alterar" href='/snep/src/ccustos.php?acao=alterar&codigo=<?php echo $val['codigo'] ?>'>
                    <?php echo $this->translate('Alterar')?>
                </a>
            </td>
            <td class="action" class="display:inline;">
                <span class="excluir"  onclick="remove_item('/snep/src/ccustos.php?acao=excluir&codigo=<?php echo $val['codigo'] ?>', '<?php echo $this->translate('Deseja realmente excluir o Centro de Custos?')?>')" >
                    <?php echo $this->translate('Excluir')?>
                </span>
            </td>
        </tr>
    <?php endforeach ?>
</table>

<?php echo $this->render('pagination.phtml') ?>