<?php
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile('/snep/includes/javascript/enableField.js');
echo $this->form;
?>

<script type="text/javascript">
    techHighlight = function() {
        $('technology-type').childElements().each(function(el){
            $$("." + el.value).each(function(el){el.hide()});
        });
        $$("." + $('technology-type').value).each(function(el){el.show()});
    }
    Event.observe($('technology-type'), 'change', techHighlight);
    Event.observe(window, 'load', techHighlight);
</script>
<script language="javascript" type="text/javascript">
    $( 'advanced-tempo').observe ('click' , init);
    Event.observe(window, 'load', init);

    function init() {
        enableField('advanced-tempo', 'advanced-time_total');
        enableField('advanced-tempo', 'advanced-time_chargeby-Y');
        enableField('advanced-tempo', 'advanced-time_chargeby-M');
        enableField('advanced-tempo', 'advanced-time_chargeby-D');
    }

    $('khomp-board').observe ('change' , fillChannels);
    Event.observe(window, 'load', fillChannels);

    function fillChannels() {

        board =   document.getElementById('khomp-board').value;
        channelValue =   document.getElementById('khomp-channel').value;
        channels =   document.getElementById('khomp-channel');
        boardsData = eval("<?= $this->boardData ?>");

        channels.length = 0;
        for (i = 0; i < boardsData[board].length; i++) {
            var y=document.createElement('option');
            y.text=i;
            y.value=i;

            channels.add(y);
        }

        if (channelValue != ''){
            channels.value = channelValue;
        }
    }
</script>