<?php
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/lib/prototype.js');
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/src/scriptaculous.js');
$this->headScript()->appendFile('/snep/includes/javascript/registrations.js');
echo $this->render('filter.phtml');

?>

<table cellspacing="0" cellpadding="0" border="0" align="center" width="100%" >
   <thead>
      <tr>
         <td class="action"> <?php echo $this->translate('Código') ?> </td>
         <td> <?php echo $this->translate('Nome') ?> </td>
         <td> <?php echo $this->translate('Tipo de Tronco') ?> </td>
         <td> <?php echo $this->translate('Tecnologia de Canais') ?> </td>
         <td class="action"> <?php echo $this->translate('Alterar') ?> </td>
         <td class="action"> <?php echo $this->translate('Excluir') ?> </td>
      </tr>
   </thead>
   <tbody>  

    <?php    
    $c = 0;
    foreach($this->trunks as $cha => $val ): ?>
        <?php ($c ? $c = 0 : $c = 1 ); ?>
        <tr class="c<?php echo $c ?>">

            <td class="action"> <b> <?php echo $val['name'] ?> </b> </td>
            <td> <b> <?php echo $val['callerid'] ?> </b> </td>
            <td>
                <?php echo ( $val['trunktype'] == "T" ?  $this->translate("TDM") : $this->translate("IP") )  ?>
            </td>
            <td> <?php echo $val['type'] ?> </td>
            <td class="action">
                <a class="alterar" href='/snep/src/troncos.php?acao=alterar&id=<?php echo $val['id'] ?>'>
                    <?php echo $this->translate('Alterar')?>
                </a>
            </td>
            <td class="action">
                <span class="excluir" onclick="remove_item('/snep/src/troncos.php?acao=excluir&id=<?php echo $val['id'] ?>&name=<?php echo $val['name'] ?>','<?php echo $this->translate("Deseja realmente excluir o Tronco?"); ?>')" >
                    <?php echo $this->translate('Excluir')?>
                </span>
            </td>
        </tr>
    <?php endforeach ?>
</table>

<?php echo $this->render('pagination.phtml') ?>