<?php
$this->headLink()->appendStylesheet( $this->baseUrl() . "/css/index.css" );
$this->headScript()->appendFile('/snep/includes/javascript/scriptaculous/lib/prototype.js');
echo $this->render('filter.phtml');
?>

<table>
   <thead>
      <tr>
         <th class="action"> <?php echo $this->translate('Code') ?> </th>
         <th> <?php echo $this->translate('Name') ?> </th>
         <th> <?php echo $this->translate('Tipo de Tronco') ?> </th>
         <th> <?php echo $this->translate('Tecnologia de Canais') ?> </th>
         <th> <?php echo $this->translate('Saldo de Tempo (min:seg)') ?> </th>
         <th colspan="2" class="action"> <?php echo $this->translate('Actions') ?>  </th>
      </tr>
   </thead>
   <tbody>
       
    <?php
    $c = 0;
    foreach($this->trunks as $id => $trunk ): ?>

        <?php ($c ? $c = 0 : $c = 1 ); ?>
        <tr class="c<?php echo $c ?>">

            <td class="numeric"> <b> <?php echo $trunk['name'] ?> </b> </td>
            <td> <?php echo $trunk['callerid'] ?> </td>
            <td>
                <?php echo ( $trunk['trunktype'] == "T" ?  $this->translate("TDM") : $this->translate("IP") )  ?>
            </td>
            <td> <?php echo $trunk['type'] ?> </td>
            <td>
                <?php if ($trunk['saldo']) : ?>
                        <?php $date = new Zend_Date( $trunk['saldo'] ) ?>
                         <span style='color:#888'> 
                            <?php echo $date->toString('H:m:s') ?>
                         </span>
                    <?php else :  ?>
                        <?php echo $this->translate('Não configurado') ?>
                <?php endif ?>
            </td>
            <td class="action">
                <a class="alterar" href="<?php echo $this->url ."/edit/trunk/".  $trunk['id'] ?>" >
                    <?php echo $this->translate('Edit')?>
                </a>
            </td>

            <td class="action">
                <a class="excluir" href="<?php echo $this->url ."/remove/id/".  $trunk['id'] . "/name/" . $trunk['name'] ?>" >
                    <?php echo $this->translate('Delete')?>
                </a>
            </td>

        </tr>
    <?php endforeach ?>
</table>

<?php echo $this->render('pagination.phtml') ?>
